import 'dart:convert';
import 'package:http/http.dart' as http;

class GithubService {
  final String _baseUrl = 'https://api.github.com';

  /// Helper to get headers for GitHub API
  Map<String, String> _getHeaders(String token) {
    return {
      'Authorization': 'Bearer $token',
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    };
  }

  /// Creates a new public repository
  Future<String> createRepository(String token, String repoName) async {
    final url = Uri.parse('$_baseUrl/user/repos');
    final response = await http.post(
      url,
      headers: _getHeaders(token),
      body: jsonEncode({
        'name': repoName,
        'description': 'Portfolio generated by Portify',
        'private': false,
        'auto_init': true, // Initializes with a README so we can push to main
      }),
    );

    if (response.statusCode == 201) {
      final data = jsonDecode(response.body);
      return data['full_name']; // e.g. "username/repoName"
    } else {
      throw Exception('Failed to create repository: ${response.body}');
    }
  }

  /// Pushes a file to the repository
  Future<void> pushFile(
    String token,
    String fullRepoName,
    String path,
    String content,
    String commitMessage,
  ) async {
    final url = Uri.parse('$_baseUrl/repos/$fullRepoName/contents/$path');
    
    // First, check if file exists to get its SHA (if we were updating)
    // For new repos, we assume the file doesn't exist yet.
    
    // Content must be base64 encoded for GitHub API
    final bytes = utf8.encode(content);
    final base64Content = base64.encode(bytes);

    final response = await http.put(
      url,
      headers: _getHeaders(token),
      body: jsonEncode({
        'message': commitMessage,
        'content': base64Content,
      }),
    );

    if (response.statusCode != 201 && response.statusCode != 200) {
      throw Exception('Failed to push file: ${response.body}');
    }
  }

  /// Enables GitHub Pages for the repository
  Future<String> enablePages(String token, String fullRepoName) async {
    final url = Uri.parse('$_baseUrl/repos/$fullRepoName/pages');
    
    final response = await http.post(
      url,
      headers: _getHeaders(token),
      body: jsonEncode({
        'source': {
          'branch': 'main',
          'path': '/',
        }
      }),
    );

    if (response.statusCode == 201) {
      final data = jsonDecode(response.body);
      return data['html_url']; // The live URL
    } else if (response.statusCode == 409) {
      // Pages already enabled or conflicting configuration
      // We can fetch the pages info instead
      final getResponse = await http.get(url, headers: _getHeaders(token));
      if (getResponse.statusCode == 200) {
        final data = jsonDecode(getResponse.body);
        return data['html_url'];
      }
      throw Exception('Failed to enable pages (conflict): ${response.body}');
    } else {
      throw Exception('Failed to enable pages: ${response.body}');
    }
  }

  /// Gets the authenticated user's profile info
  Future<Map<String, dynamic>> getUserProfile(String token) async {
    final url = Uri.parse('$_baseUrl/user');
    final response = await http.get(url, headers: _getHeaders(token));
    if (response.statusCode == 200) {
      return jsonDecode(response.body);
    } else {
      throw Exception('Failed to load user profile: ${response.body}');
    }
  }
}
