// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPi5iAjFOg1nToLMsjGtmgJL0_19tsamo',
    appId: '1:496650600840:web:ab8472ab611ef8c4b17a3d',
    messagingSenderId: '496650600840',
    projectId: 'portfoliomaker-c20c5',
    authDomain: 'portfoliomaker-c20c5.firebaseapp.com',
    storageBucket: 'portfoliomaker-c20c5.firebasestorage.app',
    measurementId: 'G-05CQE0GN75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrM-uWEhG7o0n6CODWL2yWkAYW1TD6kck',
    appId: '1:496650600840:android:43266c9875e11ad3b17a3d',
    messagingSenderId: '496650600840',
    projectId: 'portfoliomaker-c20c5',
    storageBucket: 'portfoliomaker-c20c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDc5LU-vosfJ8gDtbwdvz1JFH1COnlULg',
    appId: '1:496650600840:ios:88a623c62fcd6527b17a3d',
    messagingSenderId: '496650600840',
    projectId: 'portfoliomaker-c20c5',
    storageBucket: 'portfoliomaker-c20c5.firebasestorage.app',
    androidClientId: '496650600840-mamc5smbos7o5r3rqqkbtrpktbljhump.apps.googleusercontent.com',
    iosClientId: '496650600840-0bu1n98k3u0lge8c62e88uro9hgr1bjq.apps.googleusercontent.com',
    iosBundleId: 'com.portify.portify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDc5LU-vosfJ8gDtbwdvz1JFH1COnlULg',
    appId: '1:496650600840:ios:88a623c62fcd6527b17a3d',
    messagingSenderId: '496650600840',
    projectId: 'portfoliomaker-c20c5',
    storageBucket: 'portfoliomaker-c20c5.firebasestorage.app',
    androidClientId: '496650600840-mamc5smbos7o5r3rqqkbtrpktbljhump.apps.googleusercontent.com',
    iosClientId: '496650600840-0bu1n98k3u0lge8c62e88uro9hgr1bjq.apps.googleusercontent.com',
    iosBundleId: 'com.portify.portify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPi5iAjFOg1nToLMsjGtmgJL0_19tsamo',
    appId: '1:496650600840:web:6d216cef7a993a2eb17a3d',
    messagingSenderId: '496650600840',
    projectId: 'portfoliomaker-c20c5',
    authDomain: 'portfoliomaker-c20c5.firebaseapp.com',
    storageBucket: 'portfoliomaker-c20c5.firebasestorage.app',
    measurementId: 'G-ZW7ED40FVF',
  );
}
